### ISSUE TITLE
Move out of github pages

### ISSUE THREAD

**Issue by ipedrazas** [ipedrazas/k8s.uk#4]
It's too slow... and it would be good to be able to have some decent place to host this... like a kubernetes cluster!

**Comment by agonzalezro** [comment]
What is slow? Rendering or serving the pages?

I think that it needs some warmup if the page was inactive for a long time.

Kubernetes cluster for serving static pages seems a bit... over engineered? :D

**Comment by ipedrazas** [comment]
agreed... unless we had a cluster to run "other things"
